# Generated by Django 5.1 on 2024-09-14 09:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[200, 60], upload_to='clients/'),
        ),
    ]
