# Generated by Django 5.1 on 2024-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_client_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
