# Generated by Django 5.1 on 2024-09-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_whatido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatido',
            name='logo',
        ),
        migrations.AddField(
            model_name='whatido',
            name='icon',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
