# Generated by Django 5.1 on 2024-09-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_whatido_logo_whatido_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatido',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
