# Generated by Django 5.1 on 2024-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_whatido_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatido',
            name='icon',
            field=models.CharField(blank=True, help_text='pls visit this site   https://linearicons.com/free    to get icon', max_length=500),
        ),
    ]
