# Generated by Django 5.1 on 2024-09-16 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
