# Generated by Django 5.1 on 2024-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_certificates_date_certificates_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
