# Generated by Django 5.1 on 2024-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('proficiency_in_number', models.IntegerField()),
            ],
        ),
    ]
